### ISSUE TITLE
[suggestion] Make the 2.2 subtext be cyan

### ISSUE THREAD

**Issue by Aktimoose** [iristraa/SpinoffSubtitles#3]
I think, instead of the current green version subtext, it would be funnier to make it cyan as a reference to GD Colon's 2020 April Fools video "I Beta Tested Geometry Dash 2.2". Would also make sense to have it further to the right than it currently is.
![image](https://github.com/iristraa/SpinoffSubtitles/assets/44620677/1273ef24-4da3-4520-8bfc-5df4f9cbc34d)

**Comment by iristraa** [comment]
![image](https://github.com/iristraa/SpinoffSubtitles/assets/84076556/83e73fdd-4c33-429b-b819-391683f053da)
it does exist in the todo, stay tuned
